# Generated by Django 5.2.6 on 2026-01-02 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='accreditations',
            field=models.TextField(blank=True, help_text='Professional accreditations'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Admin approval status', max_length=10),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='licenses',
            field=models.TextField(blank=True, help_text='Professional licenses held'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
    ]
