# Generated by Django 6.0 on 2025-12-08 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_tier', models.CharField(choices=[('L1', 'FitStarter'), ('L2', 'ProActive'), ('L3', 'EliteChamp')], max_length=2)),
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('current_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('date_of_joining', models.DateField()),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('pay_monthly_in_advance', models.BooleanField(default=False)),
                ('months_selected', models.PositiveIntegerField(default=0, help_text='Number of months paid in advance')),
                ('extra_protein_needed', models.BooleanField(default=False, help_text='L2: Extra protein supplementation')),
                ('base_registration_fee', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addon_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Membership',
                'verbose_name_plural': 'User Memberships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='memberships.usermembership')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
            },
        ),
        migrations.CreateModel(
            name='L3Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('TRAINER', 'Personal Trainer Booking'), ('ZUMBA', 'Zumba & Martial Arts (Live/Recorded)'), ('NUTRITION', 'Premium Nutrition Hub (drinks + meals)'), ('WELLNESS', 'Mental Wellness Dashboard')], max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l3_addons', to='memberships.usermembership')),
            ],
            options={
                'verbose_name': 'L3 Add-on',
                'verbose_name_plural': 'L3 Add-ons',
                'unique_together': {('membership', 'addon_type')},
            },
        ),
    ]
