# Generated by Django 5.2.6 on 2025-12-23 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_l3addon_assigned_trainer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField()),
                ('checkup_type', models.CharField(help_text='Type of checkup (e.g., General, Blood Test, etc.)', max_length=200)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('findings', models.TextField(blank=True, help_text='Medical findings from the checkup')),
                ('recommendations', models.TextField(blank=True, help_text="Doctor's recommendations")),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('conducted_by', models.CharField(blank=True, help_text='Doctor/Medical professional name', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checkups', to='memberships.usermembership')),
                ('updated_by_admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkup_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Checkup',
                'verbose_name_plural': 'Medical Checkups',
                'ordering': ['-checkup_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(help_text='Week number since joining')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('start_date', models.DateField(help_text='Start date of this week')),
                ('end_date', models.DateField(help_text='End date of this week')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='memberships.usermembership')),
            ],
            options={
                'verbose_name': 'Workout Plan',
                'verbose_name_plural': 'Workout Plans',
                'ordering': ['week_number', 'day_of_week'],
                'unique_together': {('membership', 'week_number', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('exercise_type', models.CharField(choices=[('CARDIO', 'Cardio'), ('STRENGTH', 'Strength Training'), ('FLEXIBILITY', 'Flexibility'), ('HIIT', 'High Intensity Interval Training'), ('YOGA', 'Yoga'), ('CORE', 'Core Training')], max_length=20)),
                ('sets', models.PositiveIntegerField(default=1)),
                ('reps', models.PositiveIntegerField(default=1, help_text='Repetitions or duration in minutes')),
                ('description', models.TextField(blank=True, help_text='Exercise instructions')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of exercise in the plan')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='memberships.workoutplan')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['workout_plan', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProteinIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_intake', models.BooleanField(default=False, help_text='Morning protein shake taken')),
                ('evening_intake', models.BooleanField(default=False, help_text='Evening protein shake taken')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from admin')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_intakes', to='memberships.usermembership')),
                ('updated_by_admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protein Intake',
                'verbose_name_plural': 'Protein Intakes',
                'ordering': ['-date'],
                'unique_together': {('membership', 'date')},
            },
        ),
    ]
