# Generated by Django 5.2.6 on 2026-01-02 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_medicalcheckup_workoutplan_exercise_proteinintake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='payment_confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Admin notes about payment', null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Payment Confirmed'), ('CANCELLED', 'Payment Cancelled')], default='PENDING', max_length=10),
        ),
    ]
